Update theme pixel
mateusneresrb/chatgpt-style pull request #28
Opened 2023-05-15 13:14 UTC by VictorBren0

2023-05-15 13:14 UTC, VictorBren0 commented
Update

2023-05-16 18:08 UTC, mateusneresrb commented
O último commit não utiliza as classes recomendadas, realize a correção e faça outro commit

2023-05-16 18:11 UTC, mateusneresrb requested changes
Não está usando classes recomendadas

2023-05-16 18:41 UTC, mateusneresrb commented
LGTM

2023-05-16 18:42 UTC, mateusneresrb approved these changes
LGTM

2023-05-16 18:42 UTC, merged